version: "3"
services:
  gluetun:
    build:
      context: ./gluetun
      dockerfile: Dockerfile
      
    image: qmcgaw/gluetun
    container_name: gluetun_ireland
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
    ports:
      - 1083:8888/tcp # HTTP proxy
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
    volumes:
      - ./gluetun:/gluetun
    environment:
      - HTTPPROXY=on
      - SHADOWSOCKS=on
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      # - SERVER_HOSTNAMES=us10285.nordvpn.com
      - SERVER_COUNTRIES=Ireland
      # - SERVER_NUMBER=10285
      # - SERVER_COUNTRIES=United States
      # SERVER_CATEGORIES=DedicatedIP
